# .bashrc file should be place in user directory

alias ll='ls -la'
alias g='git'
alias gss='git status -sb'
alias gaa='git add --all'
alias glo='git log --oneline --decorate'
alias gcm='git commit -m'
alias gc!='git commit -v --amend'
alias gca!='git commit -v -a --amend'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gcod='git checkout develop'
alias gco='git checkout'
# delete merged branch
alias gbda='git branch --no-color --merged | command grep -vE "^(\+|\*|\s*(master|development|develop|devel|dev)\s*$)" | command xargs -n 1 git branch -d'
alias gbr='git branch --remote'
alias gcount='git shortlog -sn'
alias gd='git diff'
alias glog='git log --oneline --decorate --graph'
alias gcam='git commit -a -m'
alias gfo='git fetch origin'
alias gl='git pull'
alias greset='git reset --hard && git clean -dffx'
alias gp='git push'
alias gp!='git push --force'
alias grbi='git rebase -i'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias gupa='git pull --rebase --autostash'
